"""Generate a scenario coverage report (Story 4.1).

Writes docs/scenario-coverage.md with counts by persona, Azure product,
root-cause category, and difficulty, so distribution and gaps are visible.

Run:  uv run python scripts/coverage_report.py
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

from contoso_support_mcp.config import DEFAULT_FIXTURES_PATH
from contoso_support_mcp.data.loader import load_scenarios

OUT = Path(__file__).resolve().parents[1] / "docs" / "scenario-coverage.md"


def _table(title: str, counter: Counter) -> str:
    lines = [f"### By {title}", "", "| Value | Count |", "|-------|-------|"]
    for key, count in sorted(counter.items(), key=lambda kv: (-kv[1], str(kv[0]))):
        lines.append(f"| {key} | {count} |")
    lines.append("")
    return "\n".join(lines)


def build_report() -> str:
    dataset = load_scenarios(DEFAULT_FIXTURES_PATH)
    persona = Counter(str(s.ticket.persona) for s in dataset.scenarios)
    product = Counter(s.ticket.azure_product for s in dataset.scenarios)
    category = Counter(str(s.root_cause.category) for s in dataset.scenarios)
    difficulty = Counter(str(s.difficulty) for s in dataset.scenarios)
    total = len(dataset)
    multi = difficulty.get("multi_round", 0)
    pct = (multi / total * 100) if total else 0

    parts = [
        "# Scenario Coverage",
        "",
        "_Generated by `scripts/coverage_report.py`. Do not edit by hand._",
        "",
        f"**Total scenarios:** {total}  ",
        f"**Multi-round:** {multi} ({pct:.0f}%)",
        "",
        _table("Persona", persona),
        _table("Azure Product", product),
        _table("Root-Cause Category", category),
        _table("Difficulty", difficulty),
    ]
    return "\n".join(parts)


def main() -> None:
    OUT.write_text(build_report())
    print(f"Wrote coverage report to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
