"""Generate the instructor-facing scenario index (Story 4.4).

Writes docs/scenario-index.md: one row per scenario with id, product, persona,
difficulty, root-cause domain, title, the intended root cause (the "correct
answer" for grading), and the intended investigation tool sequence.

Run:  uv run python scripts/scenario_index.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from contoso_support_mcp.config import DEFAULT_FIXTURES_PATH
from contoso_support_mcp.data.loader import Dataset, load_scenarios

OUT = Path(__file__).resolve().parents[1] / "docs" / "scenario-index.md"


def build_index(dataset: Dataset) -> str:
    header = (
        "| Ticket | Product | Persona | Difficulty | Domain | Title "
        "| Root cause | Investigation (tool sequence) |"
    )
    sep = "|--------|---------|---------|------------|--------|-------|------------|--------|"
    lines = [
        "# Scenario Index (Instructor Reference)",
        "",
        "_Generated by `scripts/scenario_index.py`. Do not edit by hand._",
        "",
        "The **Root cause** column is the expected RCA (for grading); the "
        "**Investigation** column is the intended tool sequence.",
        "",
        header,
        sep,
    ]
    for s in dataset.scenarios:
        tools = " → ".join(step.tool for step in s.investigation_path) or "—"
        root = s.root_cause.summary.replace("\n", " ").strip()
        title = s.ticket.title.replace("\n", " ").strip()
        lines.append(
            f"| {s.ticket.ticket_id} | {s.ticket.azure_product} | {s.ticket.persona} "
            f"| {s.difficulty} | {s.root_cause.category} | {title} | {root} | {tools} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    dataset = load_scenarios(DEFAULT_FIXTURES_PATH)
    OUT.write_text(build_index(dataset))
    print(f"Wrote scenario index ({len(dataset)} rows) to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
